export const announcementsData = [
	{
		show: true,
		filterName: "announcements",
		type: "announcement",
		image: "/assets/images/blogs/Karini_Evolves_Prompting_Experience.png",
		imageAltName: "Karini AI's Enhanced Prompt Playground",
		// imageWidth: 750,
		// imageHeight: 550,
		title:
			"Karini AI unveils enhanced Prompt PlayGround, inviting Industry Experts to engage in Gen AI development",
		description:
			"Karini AI announces advanced prompt playground, encouringing industry experts to delve into the craft of prompt creation. This enhanced playground provides ready-to-use templates, user-friendly prompt creation, and a testing framework for model comparison. This allows business and technical users to quickly evaluate prompt efficacy and model performance, making the most of their domain expertise in crafting prompts.",
		tag: "Gen AI",
		date: "Jan 22nd, 2024",
		timeToRead: "2 min read",
		path: "/announcements/karini-ai-unveils-enhanced-prompt-playground",
	},
	{
		show: true,
		filterName: "announcements",
		type: "announcement",
		image: "/assets/images/blogs/Streaming-eye-catcher.png",
		imageAltName: "Karini AI Copilot Streaming Feature",
		// imageWidth: 670,
		// imageHeight: 700,
		title: "Karini AI Launches Streaming for Copilot",
		description:
			"Karini AI is proud to announce a new feature to help businesses enhance user experiences by replacing the everlasting ellipsis with streaming responses.  Following the latest trends in open-source generative artificial intelligence, this leap forward for purpose built enterprise-focused artificial intelligence using natural language questions and answers is evolving CoPilot to the next level.",
		tag: "Gen AI",
		date: "Jan 18th, 2024",
		timeToRead: "2 min read",
		path: "/announcements/karini-ai-launches-streaming-for-copilot",
	},
	{
		show: true,
		filterName: "announcements",
		type: "announcement",
		image: "/assets/images/blogs/Bedrock_Models_Support.png",
		imageAltName: 'Karini AI Amazon Bedrock Model Integration"Amazon Bedrock Models Supported by Karini AI"',
		// imageWidth: 450,
		// imageHeight: 530,
		title: "Karini AI Announces Full Support for Amazon Bedrock Models",
		description:
			"We are delighted to share that starting December 1, 2023, Karini AI has fully expanded its capabilities to support all Amazon Bedrock Models. This significant enhancement to our service offerings helps take your pilots using Amazon Bedrock faster to production.",
		tag: "Gen AI",
		date: "Dec 1st, 2023",
		timeToRead: "2 min read",
		path: "/announcements/karini-ai-announces-full-support-for-amazon-bedrock-models",
	},
	{
		show: true,
		filterName: "announcements",
		type: "announcement",
		image: "/assets/images/blogs/Databricks_Partnership.png",
		imageAltName: 'Karini AI and Databricks Partnership Logo "Innovative AI Solutions by Karini AI & Databricks"',
		// imageWidth: 530,
		// imageHeight: 530,
		title: "Karini AI Embarks on a New Partnership with Databricks",
		description:
			"We are excited to announce a dynamic new partnership between Karini AI and Databricks effective November 14, 2023. This collaboration unites the cutting-edge artificial intelligence capabilities offerered by Karini AI with the powerful Data and AI capabilities offered by Databricks to enable our customers.",
		tag: "Gen AI",
		date: "Nov 14th, 2023",
		timeToRead: "2 min read",
		path: "/announcements/karini-ai-embarks-on-a-new-partnership-with-databricks",
	},
	{
		show: true,
		filterName: "announcements",
		type: "announcement",
		image: "/assets/images/blogs/AWS_Partner_Announcement_Eye_Catcher.png",
		imageAltName:
			'Karini AI and AWS Partnership Announcement"Karini AI Logo alongside AWS Logo"',
		// imageWidth: 500,
		// imageHeight: 500,
		title:
			"Karini AI Joins Forces with Amazon Web Services as an Independent Software Vendor",
		description:
			"We are thrilled to announce that Karini AI has officially partnered with Amazon Web Services (AWS) as an Independent Software Vendor (ISV). This strategic partnership, effective from October 16, 2023, marks a significant milestone in our journey towards innovation and excellence.",
		tag: "Gen AI",
		date: "Oct 16th, 2023",
		timeToRead: "2 min read",
		path: "/announcements/karini-ai-joins-forces-with-aws-as-an-independant-software-vendor",
	},
	{
		show: true,
		filterName: "announcements",
		type: "announcement",
		image: "/assets/images/blogs/Karini AI Launches Revolutionary GenAIOps Platform (1).png",
		imageAltName:
			"Karini AI releases the first purpose-built platform for GenAIOps",
		// imageWidth: 500,
		// imageHeight: 500,
		title:
			"Karini AI releases the first purpose-built platform for GenAIOps",
		description:
			"Dateline: Alpharetta, GA, February 1, 2024–Karini.ai is excited to announce the general availability of the first-of-its-kind purpose-built Generative AI platform designed to power evolution in enterprise AI adoption. ",
		tag: "Gen AI",
		date: "Feb 1st, 2024",
		timeToRead: "2 min read",
		path: "/announcements/karini-ai-releases-the-first-purpose-built-platform-for-genaiops",
	},
];
