export const blogsFilterArray = ["all", "blogs", "announcements"];

export const blogsData = [
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/Industrialize-Generative-AI.png",
		imageAltName: 'Karini AI Generative AI Industrialization"Gen AI Integration Strategies by Karini AI"',
		// imageWidth: 400,
		// imageHeight: 400,
		title: "Industrialize Generative AI",
		description:
			"Announcing Generative AI Platform - designed to accelerate experimentation, expedite market delivery, and bridge the generative AI adoption gap, enabling businesses to harness the full potential of this groundbreaking technology.",
		tag: "Gen AI",
		date: "Jan 2nd, 2024",
		timeToRead: "5 min read",
		path: "/blogs/industrialize-generative-ai",
	},
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/Navigating_GenAIOps_in_Enterprises.png",
		imageAltName: '"Graphical Representation of GenAIOps Process""Enterprise AI Workflow Diagram by Karini AI"',
		// imageWidth: 430,
		// imageHeight: 400,
		title:
			"Navigating GenAIOps in Enterprises: Challenges and Best Practices - Version 1.0",
		description:
			"Enterprises are adopting Generative AI to help solve many complex use cases with natural language instructions. Building a Gen AI application involves multiple components such as an LLM, data sources, vector store, prompt engineering, and RAG.",
		tag: "Gen AI",
		date: "Jan 31st, 2024",
		timeToRead: "10 min read",
		path: "/blogs/navigating-genaiops-in-enterprises",
	},
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/Mastering_Generative_AI.png",
		imageAltName: "Strategies for Mastering Generative AI 'Karini AI's Guide to Gen AI Integration'",
		// imageWidth: 510,
		imageHeight: 510,
		title:
			"Mastering Generative AI: A Strategic Roadmap for Enterprise Integration",
		description:
			"In the past twelve months, the corporate landscape has been abuzz with the potential of generative AI as a groundbreaking innovation. Despite broad recognition of its transformative power, many firms have adopted a tentative stance, cautiously navigating the implementation of this technology.",
		tag: "Gen AI",
		date: "Jan 4th, 2024",
		timeToRead: "10 min read",
		path: "/blogs/mastering-generative-ai",
	},
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/Evolution_of_Gen_AI.png",
		imageAltName: "Infographic of Gen AI transforming business intelligence",
		// imageWidth: 320,
		imageHeight: 320,
		title:
			"Unleashing the Potential of Unified Data: The Gen AI Evolution in Business Intelligence",
		description:
			"In an era where data is the new gold, businesses have grappled with the challenge of data silos - isolated reservoirs of information accessible only to specific organizational factions.",
		tag: "Gen AI",
		date: "Feb 2nd, 2024",
		timeToRead: "3 min read",
		path: "/blogs/unleashing-the-potential-of-unified-data",
	},
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/Fast_track_your_prompt_Experiments.png",
		imageAltName: "Karini AI’s platform showcasing prompt engineering for AI models",
		// imageWidth: 320,
		imageHeight: 320,
		title:
			"Fast-track your Prompt Experiments by tracking the prompt runs",
		description:
			"Generative AI has sparked a wave of excitement among businesses eager to create chatbots, companions, and co-pilots for extracting insights from their data.",
		tag: "Gen AI",
		date: "Feb 26th, 2024",
		timeToRead: "5 min read",
		path: "/blogs/fast-track-your-prompt-experiments-by-tracking-the-prompt-runs",
	},
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/The_Inevitable_Disruption_copy.png",
		imageAltName: "AI transforming enterprises infographic",
		// imageWidth: 320,
		imageHeight: 320,
		title:
			"Generative AI: The Inevitable Disruption Shaping Enterprise Landscapes",
		description:
			"The business landscape is in perpetual flux, demanding constant adaptation and evolution.",
		tag: "Gen AI",
		date: "Mar 1st, 2024",
		timeToRead: "5 min read",
		path: "/blogs/generative-ai-the-inevitable-disruption",
	},
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/The_Evolution_of_AI_Agents.png",
		imageAltName: "The Evolution of AI Agents",
		// imageWidth: 320,
		imageHeight: 320,
		title:
			"From Hallucination to Human-Like Helpers: The Evolution of AI Agents",
		description:
			"The advent of Generative AI has sparked a wave of enthusiasm among businesses eager to harness its potential for creating Chatbots, companions, and copilots designed to unlock insights from vast datasets. ",
		tag: "Gen AI",
		date: "Mar 4th, 2024",
		timeToRead: "10 min read",
		path: "/blogs/the-evolution-of-ai-agents",
	},
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/Building_Efficient_RAG_Systems.png",
		imageAltName: "Building Efficient RAG Systems",
		// imageWidth: 320,
		imageHeight: 320,
		title:
			"Building Efficient RAG Systems",
		description:
			"When creating a RAG (Retrieval Augmented Generation) system, you infuse a Large Language Model (LLM) with fresh, current knowledge.",
		tag: "Gen AI",
		date: "March 13th, 2024",
		timeToRead: "3 min read",
		path: "/blogs/building-efficient-rag-systems",
	},
	{
		show: true,
		filterName: "blogs",
		type: "blog",
		image: "/assets/images/blogs/GenAI_Visibility_with_Karini_AI.png",
		imageAltName: "GenAI Visibility with Karini AI",
		// imageWidth: 320,
		imageHeight: 320,
		title:
			"GenAI Visibility: Cost transparency and consumption metrics only with Karini AI",
		description:
			"In the rapidly evolving landscape of Generative AI (Gen AI), managing the scale and cost of Large Language Models (LLMs) presents a formidable challenge for enterprises diversifying their application portfolios.",
		tag: "Gen AI",
		date: "April 12th, 2024",
		timeToRead: "4 min read",
		path: "/blogs/genai-visibility-cost-transparency-and-consumption-metrics-only-with-karini-ai",
	},
];
